def get_players():
    return [
        {"name": "Kylian Mbappe", "rating": 97, "positions": ["ST", "LW"], "nation": "france"},
        {"name": "Lamine Yamal", "rating": 97, "positions": ["RW"], "nation": "spain"},
        {"name": "Erling Haaland", "rating": 97, "positions": ["ST"], "nation": "norway"},

        {"name": "Ousmane Dembele", "rating": 96, "positions": ["ST", "RW"], "nation": "france"},
        {"name": "Michael Olise", "rating": 96, "positions": ["RW", "AM"], "nation": "france"},
        {"name": "Vitinha", "rating": 96, "positions": ["CM"], "nation": "portugal"},
        {"name": "Pedri", "rating": 96, "positions": ["CM"], "nation": "spain"},
        {"name": "Jude Bellingham", "rating": 96, "positions": ["CM", "AM"], "nation": "england"},

        {"name": "Declan Rice", "rating": 95, "positions": ["CM"], "nation": "england"},
        {"name": "Kvicha Kvaratskhelia", "rating": 95, "positions": ["LW"], "nation": "georgia"},
        {"name": "Nuno Mendes", "rating": 95, "positions": ["LB"], "nation": "portugal"},
        {"name": "Achraf Hakimi", "rating": 95, "positions": ["RB"], "nation": "morocco"},

        {"name": "Vinicius Jr", "rating": 94, "positions": ["LW"], "nation": "brazil"},
        {"name": "Harry Kane", "rating": 94, "positions": ["ST"], "nation": "england"},
        {"name": "William Saliba", "rating": 94, "positions": ["CB"], "nation": "france"},
        {"name": "Gabriel Magalhaes", "rating": 94, "positions": ["CB"], "nation": "brazil"},
        {"name": "Joao Neves", "rating": 94, "positions": ["CM"], "nation": "portugal"},
        {"name": "Desire Doue", "rating": 94, "positions": ["RW", "LW"], "nation": "france"},

        {"name": "Fede Valverde", "rating": 93, "positions": ["CM", "RB"], "nation": "uruguay"},
        {"name": "Raphinha", "rating": 93, "positions": ["LW", "RW"], "nation": "brazil"},
        {"name": "Willian Pacho", "rating": 93, "positions": ["CB"], "nation": "ecuador"},
        {"name": "Luis Diaz", "rating": 93, "positions": ["LW"], "nation": "colombia"},
        {"name": "Virgil Van Dijk", "rating": 93, "positions": ["CB"], "nation": "netherlands"},

        {"name": "Bruno Fernandes", "rating": 92, "positions": ["AM"], "nation": "portugal"},
        {"name": "Julian Alvarez", "rating": 92, "positions": ["ST"], "nation": "argentina"},
        {"name": "Aurelien Tchouameni", "rating": 92, "positions": ["CM"], "nation": "france"},
        {"name": "David Raya", "rating": 92, "positions": ["GK"], "nation": "spain"},

        {"name": "Dayot Upamecano", "rating": 91, "positions": ["CB"], "nation": "france"},
        {"name": "Joshua Kimmich", "rating": 91, "positions": ["CM", "RB"], "nation": "germany"},
        {"name": "Nico O'Reilly", "rating": 91, "positions": ["LB"], "nation": "england"},
        {"name": "Joan Garcia", "rating": 91, "positions": ["GK"], "nation": "spain"},

        {"name": "Arda Guler", "rating": 90, "positions": ["CM", "AM"], "nation": "turkey"},
        {"name": "Thibaut Courtois", "rating": 90, "positions": ["GK"], "nation": "belgium"},
        {"name": "Dominik Szoboszlai", "rating": 90, "positions": ["CM", "AM"], "nation": "hungary"},
        {"name": "Jurien Timber", "rating": 90, "positions": ["RB", "CB"], "nation": "netherlands"},

        {"name": "Bukayo Saka", "rating": 89, "positions": ["RW"], "nation": "england"},
        {"name": "Rodri", "rating": 89, "positions": ["CM"], "nation": "spain"},
        {"name": "Ryan Gravenberch", "rating": 89, "positions": ["CM"], "nation": "netherlands"},
        {"name": "Jonathan Tah", "rating": 89, "positions": ["CB"], "nation": "germany"},
        {"name": "Yan Diomande", "rating": 89, "positions": ["LW", "RW"], "nation": "ivorycoast"},
        {"name": "Aleksandar Pavlovic", "rating": 89, "positions": ["CM"], "nation": "germany"},
        {"name": "Frenkie De Jong", "rating": 89, "positions": ["CM"], "nation": "netherlands"},

        {"name": "Rayan Cherki", "rating": 88, "positions": ["AM", "RW"], "nation": "france"},
        {"name": "Moises Caicedo", "rating": 88, "positions": ["CM"], "nation": "ecuador"},
        {"name": "Marc Cucurella", "rating": 88, "positions": ["LB"], "nation": "spain"},
        {"name": "Kenan Yildiz", "rating": 88, "positions": ["LW", "RW"], "nation": "turkey"},
        {"name": "Trent Alexander-Arnold", "rating": 88, "positions": ["RB"], "nation": "england"},
        {"name": "Ademola Lookman", "rating": 88, "positions": ["LW"], "nation": "nigeria"},
        {"name": "Marc Guehi", "rating": 88, "positions": ["CB"], "nation": "england"},
        {"name": "Fermin Lopez", "rating": 88, "positions": ["AM"], "nation": "spain"},
        {"name": "Jeremy Doku", "rating": 88, "positions": ["LW"], "nation": "belgium"},

        {"name": "Bernardo Silva", "rating": 87, "positions": ["CM"], "nation": "portugal"},
        {"name": "Cole Palmer", "rating": 87, "positions": ["AM", "RW"], "nation": "england"},
        {"name": "Jamal Musiala", "rating": 87, "positions": ["AM"], "nation": "germany"},
        {"name": "Enzo Fernandez", "rating": 87, "positions": ["CM"], "nation": "argentina"},
        {"name": "Denzel Dumfries", "rating": 87, "positions": ["RB"], "nation": "netherlands"},
        {"name": "Lautaro Martinez", "rating": 87, "positions": ["ST"], "nation": "argentina"},
        {"name": "Josko Gvardiol", "rating": 87, "positions": ["LB", "CB"], "nation": "croatia"},
        {"name": "Ruben Dias", "rating": 87, "positions": ["CB"], "nation": "portugal"},
        {"name": "Fabian Ruiz", "rating": 87, "positions": ["CM"], "nation": "spain"},
        {"name": "Mattheus Cunha", "rating": 87, "positions": ["ST", "LW"], "nation": "brazil"},
        {"name": "Ibrahima Konate", "rating": 87, "positions": ["CB"], "nation": "france"},
        {"name": "Elliot Anderson", "rating": 87, "positions": ["CM"], "nation": "england"},

        {"name": "Alisson Becker", "rating": 86, "positions": ["GK"], "nation": "brazil"},
        {"name": "Kai Havertz", "rating": 86, "positions": ["ST", "AM"], "nation": "germany"},
        {"name": "Joao Pedro", "rating": 86, "positions": ["ST", "AM"], "nation": "brazil"},
        {"name": "Alexis MacAllister", "rating": 86, "positions": ["CM", "AM"], "nation": "argentina"},
        {"name": "Reece James", "rating": 86, "positions": ["RB", "CM"], "nation": "england"},
        {"name": "Federico Dimarco", "rating": 86, "positions": ["LB"], "nation": "italy"},
        {"name": "Serge Gnabry", "rating": 86, "positions": ["RW", "AM"], "nation": "germany"},
        {"name": "Pau Cubarsi", "rating": 86, "positions": ["CB"], "nation": "spain"},
        {"name": "Marcos Llorente", "rating": 86, "positions": ["CM", "RB"], "nation": "spain"},
        {"name": "Sandro Tonali", "rating": 86, "positions": ["CM"], "nation": "italy"},
        {"name": "Jules Kounde", "rating": 86, "positions": ["RB"], "nation": "france"},
        {"name": "Hugo Ekitike", "rating": 86, "positions": ["ST", "LW"], "nation": "france"},
        {"name": "Marcus Rashford", "rating": 86, "positions": ["LW", "ST"], "nation": "england"},
        {"name": "Konrad Laimer", "rating": 86, "positions": ["RB", "CM"], "nation": "austria"},
        {"name": "Antoine Semenyo", "rating": 86, "positions": ["RW", "LW"], "nation": "ghana"},
        
        {"name": "Florian Wirtz", "rating": 85, "positions": ["AM"], "nation": "germany"},
        {"name": "Mike Maignan", "rating": 85, "positions": ["GK"], "nation": "france"},
        {"name": "Eberechi Eze", "rating": 85, "positions": ["AM", "LW"], "nation": "england"},
        {"name": "Antonio Rudiger", "rating": 85, "positions": ["CB"], "nation": "germany"},
        {"name": "Alejandro Grimaldo", "rating": 85, "positions": ["LB"], "nation": "spain"},
        {"name": "Marcus Thuram", "rating": 85, "positions": ["ST"], "nation": "france"},
        {"name": "Martin Odegaard", "rating": 85, "positions": ["CM", "AM"], "nation": "norway"},
        {"name": "Mickey Van de Ven", "rating": 85, "positions": ["CB", "LB"], "nation": "netherlands"},
        {"name": "Brahim Diaz", "rating": 85, "positions": ["RW", "AM"], "nation": "morocco"},
        {"name": "Alexander Isak", "rating": 85, "positions": ["ST"], "nation": "sweden"},
        {"name": "Joao Cancelo", "rating": 85, "positions": ["RB", "LB"], "nation": "portugal"},
        {"name": "Alexander Sorloth", "rating": 85, "positions": ["ST"], "nation": "norway"},
        {"name": "Bradley Barcola", "rating": 85, "positions": ["LW", "RW"], "nation": "france"},
        {"name": "Scott Mctominay", "rating": 85, "positions": ["CM", "AM"], "nation": "scotland"},
        {"name": "Alessandro Bastoni", "rating": 85, "positions": ["CB"], "nation": "italy"},
        {"name": "Granit Xhaka", "rating": 85, "positions": ["CM"], "nation": "switzerland"},
        {"name": "Martin Zubimendi", "rating": 85, "positions": ["CM"], "nation": "spain"},

        {"name": "Ferran Torres", "rating": 84, "positions": ["ST"], "nation": "spain"},
        {"name": "Lewis Hall", "rating": 84, "positions": ["LB"], "nation": "england"},
        {"name": "Leandro Trossard", "rating": 84, "positions": ["LW"], "nation": "belgium"},
        {"name": "Victor Gyokeres", "rating": 84, "positions": ["ST"], "nation": "sweden"},
        {"name": "Cristian Romero", "rating": 84, "positions": ["CB"], "nation": "argentina"},
        {"name": "Josip Stanisic", "rating": 84, "positions": ["RB"], "nation": "croatia"},
        {"name": "Alejandro Balde", "rating": 84, "positions": ["LB"], "nation": "spain"},
        {"name": "John McGinn", "rating": 84, "positions": ["CM", "AM"], "nation": "scotland"},
        {"name": "Ezra Konsa", "rating": 84, "positions": ["CB", "RB"], "nation": "england"},
        {"name": "Mikel Merino", "rating": 84, "positions": ["CM", "AM"], "nation": "spain"},
        {"name": "Cody Gakpo", "rating": 84, "positions": ["LW", "ST"], "nation": "netherlands"},
        {"name": "Felix Nmecha", "rating": 84, "positions": ["CM"], "nation": "germany"},
        {"name": "Rasmus Hojlund", "rating": 84, "positions": ["ST"], "nation": "denmark"},
        {"name": "Riccardo Calafiori", "rating": 84, "positions": ["LB", "CB"], "nation": "italy"},
        {"name": "Adrien Rabiot", "rating": 84, "positions": ["CM"], "nation": "france"},
        {"name": "Morgan Rogers", "rating": 84, "positions": ["AM"], "nation": "england"},

        {"name": "Rafael Leao", "rating": 83, "positions": ["LW", "ST"], "nation": "portugal"},
        {"name": "Gianluigi Donnarumma", "rating": 83, "positions": ["GK"], "nation": "italy"},
        {"name": "Nicolo Barella", "rating": 83, "positions": ["CM"], "nation": "italy"},
        {"name": "Bruno Guimaraes", "rating": 83, "positions": ["CM"], "nation": "brazil"},
        {"name": "Alex Baena", "rating": 83, "positions": ["AM", "LW"], "nation": "spain"},
        {"name": "Youri Tielemans", "rating": 83, "positions": ["CM"], "nation": "belgium"},
        {"name": "Eduardo Camavinga", "rating": 83, "positions": ["CM"], "nation": "france"},
        {"name": "Manuel Neuer", "rating": 83, "positions": ["GK"], "nation": "germany"},
        {"name": "Rodrygo", "rating": 83, "positions": ["RW", "LW"], "nation": "brazil"},
        {"name": "Phil Foden", "rating": 83, "positions": ["AM"], "nation": "england"},
        {"name": "Harry Maguire", "rating": 83, "positions": ["CB"], "nation": "england"},

        {"name": "Xavi Simons", "rating": 82, "positions": ["AM"], "nation": "netherlands"},
        {"name": "Pedro Neto", "rating": 82, "positions": ["LW", "RW"], "nation": "portugal"},
        {"name": "Malo Gusto", "rating": 82, "positions": ["RB"], "nation": "france"},
        {"name": "Serhou Guirassy", "rating": 82, "positions": ["ST"], "nation": "guinea"},
        {"name": "Victor Lindelof", "rating": 82, "positions": ["CB", "CM"], "nation": "sweden"},
        {"name": "Gabriel Martinelli", "rating": 82, "positions": ["LW"], "nation": "brazil"},
        {"name": "Manuel Akanji", "rating": 82, "positions": ["CB"], "nation": "switzerland"},
        {"name": "Yann Sommer", "rating": 82, "positions": ["GK"], "nation": "switzerland"},
        {"name": "Christian Pulisic", "rating": 82, "positions": ["LW", "RW"], "nation": "america"},
        {"name": "Luke Shaw", "rating": 82, "positions": ["LB"], "nation": "england"},
        {"name": "Mateo Kovacic", "rating": 82, "positions": ["CM"], "nation": "croatia"},

        {"name": "Mikel Oyarzabal", "rating": 81, "positions": ["ST"], "nation": "spain"},
        {"name": "Richarlison", "rating": 81, "positions": ["ST"], "nation": "brazil"},
        {"name": "Andrew Robertson", "rating": 81, "positions": ["LB"], "nation": "scotland"},
        {"name": "Abdukodir Khusanov", "rating": 81, "positions": ["CB"], "nation": "uzbekistan"},
        {"name": "Gregor Kobel", "rating": 81, "positions": ["GK"], "nation": "switzerland"},
        {"name": "Karim Adeyemi", "rating": 81, "positions": ["ST", "AM"], "nation": "germany"},
        {"name": "Hakan Calhanoglu", "rating": 81, "positions": ["CM"], "nation": "turkey"},
        {"name": "Marcel Sabitzer", "rating": 81, "positions": ["CM"], "nation": "austria"},
        {"name": "Kaoru Mitoma", "rating": 81, "positions": ["LW"], "nation": "japan"},
        {"name": "Jadon Sancho", "rating": 81, "positions": ["LW", "RW"], "nation": "england"},
        {"name": "Savinho", "rating": 81, "positions": ["RW"], "nation": "brazil"},
        {"name": "Nathan Ake", "rating": 81, "positions": ["CB", "LB"], "nation": "netherlands"},

        {"name": "Westin Mckennie", "rating": 80, "positions": ["CM"], "nation": "america"},
        {"name": "Connor Gallagher", "rating": 80, "positions": ["CM"], "nation": "england"},
        {"name": "Joao Palhinha", "rating": 80, "positions": ["CM"], "nation": "portugal"},
        {"name": "Fran Garcia", "rating": 80, "positions": ["LB"], "nation": "spain"},
        {"name": "Randal Kolo Muani", "rating": 80, "positions": ["ST"], "nation": "france"},
        {"name": "Diogo Dalot", "rating": 80, "positions": ["RB", "LB"], "nation": "portugal"},
        {"name": "Curtis Jones", "rating": 80, "positions": ["CM"], "nation": "england"},
        {"name": "Wesley Fofana", "rating": 80, "positions": ["CB"], "nation": "france"},
        {"name": "Nicolas Jackson", "rating": 80, "positions": ["ST"], "nation": "senegal"},
        {"name": "Alejandro Garnacho", "rating": 80, "positions": ["LW", "RW"], "nation": "argentina"},
        {"name": "Lucas Beraldo", "rating": 80, "positions": ["CB"], "nation": "brazil"},
        {"name": "Manuel Ugarte", "rating": 80, "positions": ["CM"], "nation": "uruguay"},
        {"name": "Kepa Arrizabalaga", "rating": 80, "positions": ["GK"], "nation": "spain"},
    ]




